export const LEGACY_ADMIN_GROUPS = [
  {
    title: 'Users and Access',
    items: [
      { label: 'Users', href: '/vicidial/admin.php?ADD=0A' },
      { label: 'Add User', href: '/vicidial/admin.php?ADD=1' },
      { label: 'User Groups', href: '/vicidial/admin.php?ADD=100000' },
      { label: 'Add User Group', href: '/vicidial/admin.php?ADD=111111' },
      { label: 'Remote Agents', href: '/vicidial/admin.php?ADD=10000' },
      { label: 'Extension Groups', href: '/vicidial/admin.php?ADD=12000' },
    ],
  },
  {
    title: 'Campaigns and Leads',
    items: [
      { label: 'Campaigns', href: '/vicidial/admin.php?ADD=10' },
      { label: 'Add Campaign', href: '/vicidial/admin.php?ADD=11' },
      { label: 'Lists', href: '/vicidial/admin.php?ADD=100' },
      { label: 'Add List', href: '/vicidial/admin.php?ADD=111' },
      { label: 'Drop Lists', href: '/vicidial/admin.php?ADD=130' },
      { label: 'DNC', href: '/vicidial/admin.php?ADD=121' },
      { label: 'Scripts', href: '/vicidial/admin.php?ADD=1000000' },
      { label: 'Filters', href: '/vicidial/admin.php?ADD=10000000' },
    ],
  },
  {
    title: 'Inbound Routing',
    items: [
      { label: 'In-Groups', href: '/vicidial/admin.php?ADD=1000' },
      { label: 'Add In-Group', href: '/vicidial/admin.php?ADD=1111' },
      { label: 'DIDs', href: '/vicidial/admin.php?ADD=1300' },
      { label: 'Add DID', href: '/vicidial/admin.php?ADD=1311' },
      { label: 'Call Menus', href: '/vicidial/admin.php?ADD=1500' },
      { label: 'Add Call Menu', href: '/vicidial/admin.php?ADD=1511' },
      { label: 'Filter Phone Groups', href: '/vicidial/admin.php?ADD=1700' },
      { label: 'Email In-Groups', href: '/vicidial/admin.php?ADD=1800' },
      { label: 'Chat In-Groups', href: '/vicidial/admin.php?ADD=1900' },
    ],
  },
  {
    title: 'Platform',
    items: [
      { label: 'Phones', href: '/vicidial/admin.php?ADD=10000000000' },
      { label: 'Phone Aliases', href: '/vicidial/admin.php?ADD=12000000000' },
      { label: 'Group Aliases', href: '/vicidial/admin.php?ADD=13000000000' },
      { label: 'Servers', href: '/vicidial/admin.php?ADD=100000000000' },
      { label: 'Carriers', href: '/vicidial/admin.php?ADD=140000000000' },
      { label: 'Conferences', href: '/vicidial/admin.php?ADD=1000000000000' },
      { label: 'Agent Conferences', href: '/vicidial/admin.php?ADD=10000000000000' },
      { label: 'Conf Templates', href: '/vicidial/admin.php?ADD=130000000000' },
    ],
  },
  {
    title: 'System Configuration',
    items: [
      { label: 'Call Times', href: '/vicidial/admin.php?ADD=100000000' },
      { label: 'State Call Times', href: '/vicidial/admin.php?ADD=1000000000' },
      { label: 'Shifts', href: '/vicidial/admin.php?ADD=130000000' },
      { label: 'System Settings', href: '/vicidial/admin.php?ADD=311111111111111' },
      { label: 'System Statuses', href: '/vicidial/admin.php?ADD=321111111111111' },
      { label: 'Status Groups', href: '/vicidial/admin.php?ADD=193000000000' },
      { label: 'Screen Labels', href: '/vicidial/admin.php?ADD=180000000000' },
      { label: 'Screen Colors', href: '/vicidial/admin.php?ADD=182000000000' },
      { label: 'Settings Containers', href: '/vicidial/admin.php?ADD=192000000000' },
    ],
  },
  {
    title: 'Media and Tools',
    items: [
      { label: 'Music On Hold', href: '/vicidial/admin.php?ADD=160000000000' },
      { label: 'Text To Speech', href: '/vicidial/admin.php?ADD=150000000000' },
      { label: 'Voicemail', href: '/vicidial/admin.php?ADD=170000000000' },
      { label: 'VM Message Groups', href: '/vicidial/admin.php?ADD=197000000000' },
      { label: 'CID Groups', href: '/vicidial/admin.php?ADD=196000000000' },
      { label: 'Queue Groups', href: '/vicidial/admin.php?ADD=198000000000' },
      { label: 'Contacts', href: '/vicidial/admin.php?ADD=190000000000' },
      { label: 'Automated Reports', href: '/vicidial/admin.php?ADD=194000000000' },
      { label: 'IP Lists', href: '/vicidial/admin.php?ADD=195000000000' },
      { label: 'Languages', href: '/vicidial/admin_languages.php?ADD=163000000000' },
      { label: 'Audio Soundboards', href: '/vicidial/admin_soundboard.php?ADD=162000000000' },
    ],
  },
];

export const REPORT_GROUPS = [
  {
    title: 'Real-Time',
    items: [
      { label: 'Real-Time Main', href: '/vicidial/realtime_report.php?report_display_type=HTML' },
      { label: 'Campaign Summary', href: '/vicidial/AST_timeonVDADallSUMMARY.php' },
      { label: 'Whiteboard', href: '/vicidial/AST_rt_whiteboard_rpt.php' },
      { label: 'Agent Monitor Log', href: '/vicidial/AST_rt_monitor_log_report.php' },
    ],
  },
  {
    title: 'Inbound',
    items: [
      { label: 'Inbound Report', href: '/vicidial/AST_CLOSERstats.php' },
      { label: 'Inbound v2', href: '/vicidial/AST_CLOSERstats_v2.php' },
      { label: 'Service Level', href: '/vicidial/AST_CLOSER_service_level.php' },
      { label: 'Hourly Summary', href: '/vicidial/AST_CLOSERsummary_hourly.php' },
      { label: 'Daily Summary', href: '/vicidial/AST_inbound_daily_report.php' },
      { label: 'DID Report', href: '/vicidial/AST_DIDstats.php' },
      { label: 'DID Summary', href: '/vicidial/AST_DIDstats_v2.php' },
      { label: 'DID Detail', href: '/vicidial/AST_DIDdetail.php' },
      { label: 'IVR Report', href: '/vicidial/AST_IVRstats.php' },
      { label: 'Forecasting', href: '/vicidial/AST_inbound_forecasting.php' },
    ],
  },
  {
    title: 'Outbound and Lists',
    items: [
      { label: 'Outbound Calling', href: '/vicidial/AST_VDADstats.php' },
      { label: 'Outbound Interval', href: '/vicidial/AST_OUTBOUNDsummary_interval.php' },
      { label: 'Outbound IVR', href: '/vicidial/AST_IVRstats.php?type=outbound' },
      { label: 'Lead Source', href: '/vicidial/AST_source_vlc_status_report.php' },
      { label: 'Hopper List', href: '/vicidial/AST_VICIDIAL_hopperlist.php' },
      { label: 'List Statuses', href: '/vicidial/AST_LISTS_stats.php' },
      { label: 'List Campaign Statuses', href: '/vicidial/AST_LISTS_campaign_stats.php' },
      { label: 'Campaign Status List', href: '/vicidial/AST_campaign_status_list_report.php' },
      { label: 'Dialer Inventory', href: '/vicidial/AST_dialer_inventory_report.php' },
    ],
  },
  {
    title: 'Agents and Teams',
    items: [
      { label: 'Agent Time Detail', href: '/vicidial/AST_agent_time_detail.php' },
      { label: 'Agent Status Detail', href: '/vicidial/AST_agent_status_detail.php' },
      { label: 'Agent Performance Detail', href: '/vicidial/AST_agent_performance_detail.php' },
      { label: 'Agent Performance', href: '/vicidial/AST_agent_performance.php' },
      { label: 'Team Performance', href: '/vicidial/AST_team_performance_detail.php' },
      { label: 'Performance Comparison', href: '/vicidial/AST_performance_comparison_report.php' },
      { label: 'Single Agent Daily', href: '/vicidial/AST_agent_days_detail.php' },
      { label: 'Single Agent Time', href: '/vicidial/AST_agent_days_time.php' },
      { label: 'User Group Login', href: '/vicidial/AST_usergroup_login_report.php' },
      { label: 'User Group Hourly', href: '/vicidial/AST_user_group_hourly_detail.php' },
      { label: 'User Logins', href: '/vicidial/user_logins_report.php' },
      { label: 'Agent Disposition', href: '/vicidial/AST_agent_disposition.php' },
    ],
  },
  {
    title: 'Exports',
    items: [
      { label: 'Export Calls', href: '/vicidial/call_report_export.php' },
      { label: 'Export Calls by Carrier', href: '/vicidial/call_report_export_carrier.php' },
      { label: 'Export Leads', href: '/vicidial/lead_report_export.php' },
      { label: 'Callbacks Export', href: '/vicidial/callbacks_export.php' },
      { label: 'CallCard Export', href: '/vicidial/callcard_report_export.php' },
      { label: 'Called Counts List IDs', href: '/vicidial/called_counts_multilist_report.php' },
    ],
  },
  {
    title: 'Logs and QA',
    items: [
      { label: 'Administration Change Log', href: '/vicidial/AST_admin_report.php' },
      { label: 'Recording Access Log', href: '/vicidial/AST_recording_log_report.php' },
      { label: 'API Log', href: '/vicidial/AST_API_log_report.php' },
      { label: 'Agent Debug Log', href: '/vicidial/AST_agent_debug_log_report.php' },
      { label: 'Dial Log', href: '/vicidial/AST_dial_log_report.php' },
      { label: 'Carrier Log', href: '/vicidial/AST_carrier_log_report.php' },
      { label: 'Hangup Cause', href: '/vicidial/AST_hangup_cause_report.php' },
      { label: 'SIP Event', href: '/vicidial/AST_SIP_event_report.php' },
      { label: 'AMD Log', href: '/vicidial/AST_AMD_log_report.php' },
      { label: '3-Way Press Log', href: '/vicidial/AST_3way_press_log_report.php' },
      { label: 'Quality Control', href: '/vicidial/AST_quality_control_report.php' },
      { label: 'Agent Chat Log', href: '/vicidial/AST_chat_log_report.php' },
    ],
  },
  {
    title: 'System',
    items: [
      { label: 'Server Performance', href: '/vicidial/AST_server_performance.php' },
      { label: 'Maximum System Stats', href: '/vicidial/admin.php?ADD=999992&stage=TOTAL' },
      { label: 'Maximum Stats Detail', href: '/vicidial/admin.php?ADD=999993' },
      { label: 'Phone Stats', href: '/vicidial/phone_stats.php' },
      { label: 'Process Report', href: '/vicidial/process_report.php' },
      { label: 'SPH Report', href: '/vicidial/sph_report.php' },
      { label: 'Medialog Inventory', href: '/vicidial/medialog_inventory_report.php' },
      { label: 'Webserver URL', href: '/vicidial/AST_webserver_url_report.php' },
      { label: 'URL Log', href: '/vicidial/AST_url_log_report.php' },
      { label: 'Demographic Quotas', href: '/vicidial/demographic_quotas_report.php' },
      { label: 'Khomp Quick Stats', href: '/vicidial/khomp_quick_stats.php' },
    ],
  },
];
