#!/usr/bin/env python3
"""GenX multi-campaign demo data — backfill + daily refresh (campaign filtering / future multi-tenant).

Creates several demo campaigns (each a future "tenant": its own user_group, lists,
agents and lead pool) by CLONING the stock TESTCAMP row, then generates outbound
call history (vicidial_log + carrier/dial/agent/recording) per campaign per day.

Everything it writes is tagged so it is fully reversible and idempotent:
  - vicidial_log / vicidial_agent_log rows carry comments='DEMODAILY'
  - carrier_log / dial_log caller_code and every uniqueid start with 'MD'
  - recording_log.vicidial_id starts with 'MD'
A day is regenerated by DELETE-then-INSERT on those markers, so re-running any day
(or the hourly cron) never duplicates. DEMO6M (the 6-month TESTCAMP scale set) and
real traffic are left untouched.

Usage (emits SQL on stdout — pipe into mysql as root on the UI's DB, db1):
    genx-demo-daily.py --setup            | mysql -u root asterisk   # campaigns+lists+agents+leads only
    genx-demo-daily.py --backfill 35      | mysql -u root asterisk   # setup + last 35 days .. today
    genx-demo-daily.py --date 2026-07-18  | mysql -u root asterisk   # one specific day (no setup)
    genx-demo-daily.py                    | mysql -u root asterisk   # today only (cron default, no setup)

Deterministic per (campaign, day) via a seed derived from the date, so re-running a
day reproduces the same shape.
"""
import argparse
import random
import sys
import time
from datetime import date, datetime, timedelta

W = sys.stdout.write

SIP = '74.208.179.214'
HOST = 'admin.viciboxclone.genxcontactcenter.com'
AUDIO_DIR = '5mc4n12k5tgfqng9tqppw0fd0ft1mx'
AUDIO = ['0.wav', '1.wav', '2.wav', '3.wav', '1-yes-2-no.wav']
CLONE_FROM = 'TESTCAMP'            # stock campaign whose 370 columns we copy
LEADS_PER_LIST = 20_000

FIRST = ['James', 'Mary', 'Robert', 'Patricia', 'John', 'Jennifer', 'Michael', 'Linda', 'David', 'Elizabeth',
         'William', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica', 'Thomas', 'Sarah', 'Carlos', 'Maria',
         'Kevin', 'Nancy', 'Brian', 'Lisa', 'Angela', 'Mark', 'Sandra', 'Eric', 'Ashley', 'Laura']
LAST = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez',
        'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
        'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson']
STATES = [('IL', 'Chicago', '60601', '-5.00'), ('NY', 'New York', '10001', '-4.00'),
          ('CA', 'Los Angeles', '90001', '-7.00'), ('TX', 'Dallas', '75201', '-5.00'),
          ('FL', 'Miami', '33101', '-4.00'), ('OH', 'Columbus', '43004', '-4.00'),
          ('GA', 'Atlanta', '30301', '-4.00'), ('AZ', 'Phoenix', '85001', '-7.00')]

# 1000-slot outbound status lookup (share per mille):
# status, handled(agent), lo_len, hi_len, dialstatus, hangup_cause, sip_cause, sip_reason, answered
OUT = []
def _add(status, permille, handled, lo, hi, dialstatus, cause, sip, reason, answered):
    OUT.extend([(status, handled, lo, hi, dialstatus, cause, sip, reason, answered)] * permille)
_add('NA', 448, False, 15, 35, 'NOANSWER', 19, 480, 'Temporarily Unavailable', False)
_add('AA', 240, False, 25, 50, 'ANSWER', 16, 200, 'OK', True)
_add('B', 70, False, 8, 20, 'BUSY', 17, 486, 'Busy Here', False)
_add('N', 60, False, 5, 15, 'CHANUNAVAIL', 19, 487, 'Request Terminated', False)
_add('DROP', 35, False, 3, 25, 'ANSWER', 16, 200, 'OK', True)
_add('PU', 22, True, 40, 120, 'ANSWER', 16, 200, 'OK', True)
_add('DC', 18, True, 30, 90, 'ANSWER', 16, 200, 'OK', True)
_add('NI', 36, True, 90, 300, 'ANSWER', 16, 200, 'OK', True)
_add('SALE', 8, True, 240, 700, 'ANSWER', 16, 200, 'OK', True)
_add('CALLBK', 12, True, 60, 240, 'ANSWER', 16, 200, 'OK', True)
_add('DNC', 4, True, 30, 90, 'ANSWER', 16, 200, 'OK', True)
_add('NA', 1000 - len(OUT), False, 15, 35, 'NOANSWER', 19, 480, 'Temporarily Unavailable', False)

LEAD_STATUSES = (['NEW'] * 200 + ['NA'] * 300 + ['AA'] * 160 + ['NI'] * 90 + ['PU'] * 60 + ['B'] * 50
                 + ['SALE'] * 25 + ['CALLBK'] * 35 + ['DC'] * 30 + ['N'] * 25 + ['DROP'] * 15 + ['DNC'] * 10)

# --- the tenants -------------------------------------------------------------
# active_from: the earliest day this campaign emits data (TESTCAMP resumes the
# day after DEMO6M ends so there is no visible gap and no overlap with the bulk).
CAMPAIGNS = [
    {'id': 'DEMOAUTO',  'name': 'Demo - Auto Warranty', 'group': 'DEMO_AUTO',  'group_name': 'Tenant - Auto Warranty',
     'lists': [(201, 'Auto Warranty Fresh'), (202, 'Auto Warranty Aged')],   'agents': (3101, 12), 'vol': 10_000, 'active_from': None},
    {'id': 'DEMOSOLAR', 'name': 'Demo - Solar',          'group': 'DEMO_SOLAR', 'group_name': 'Tenant - Solar',
     'lists': [(211, 'Solar West'), (212, 'Solar East')],                     'agents': (3201, 10), 'vol': 7_000,  'active_from': None},
    {'id': 'DEMOMEDI',  'name': 'Demo - Medicare',       'group': 'DEMO_MEDI',  'group_name': 'Tenant - Medicare',
     'lists': [(221, 'Medicare T1'), (222, 'Medicare T2')],                   'agents': (3301, 15), 'vol': 12_000, 'active_from': None},
    {'id': 'DEMOINS',   'name': 'Demo - Insurance',      'group': 'DEMO_INS',   'group_name': 'Tenant - Insurance',
     'lists': [(231, 'Insurance Aged'), (232, 'Insurance Fresh')],            'agents': (3401, 8),  'vol': 5_000,  'active_from': None},
    {'id': 'DEMOFIN',   'name': 'Demo - Finance',        'group': 'DEMO_FIN',   'group_name': 'Tenant - Finance',
     'lists': [(241, 'Finance A'), (242, 'Finance B')],                       'agents': (3501, 6),  'vol': 4_000,  'active_from': None},
    # The stock flagship — kept fresh going forward, but only from the day after
    # the DEMO6M bulk ends so we never inflate its historical curve.
    {'id': 'TESTCAMP',  'name': None, 'group': 'ADMIN', 'group_name': None,
     'lists': [], 'agents': (1001, 60), 'vol': 25_000, 'active_from': date(2026, 7, 14), 'existing': True},
]


class Tbl:
    def __init__(self, table, cols, cap=1000):
        self.head = f'INSERT INTO {table} ({cols}) VALUES\n'
        self.rows, self.cap, self.count = [], cap, 0
    def add(self, row):
        self.rows.append(row)
        self.count += 1
        if len(self.rows) >= self.cap:
            self.flush()
    def flush(self):
        if self.rows:
            W(self.head + ',\n'.join(self.rows) + ';\n')
            self.rows = []


def agent_ids(camp):
    start, n = camp['agents']
    return [str(start + i) for i in range(n)]


def lead_range(list_id):
    base = list_id * 100_000          # e.g. list 201 -> 20,100,000 .. 20,119,999 (no clash with DEMO6M 1M-4M)
    return base, base + LEADS_PER_LIST


def emit_setup(with_leads):
    """Idempotent: user_groups, cloned campaigns, lists, agents, and (optionally) leads."""
    W('-- ===== demo multi-campaign setup (idempotent) =====\n')
    for c in CAMPAIGNS:
        if c.get('existing'):
            continue
        W(f"INSERT IGNORE INTO vicidial_user_groups (user_group, group_name, allowed_campaigns) "
          f"VALUES ('{c['group']}','{c['group_name']}','-ALL-CAMPAIGNS-');\n")
        # Clone the 370-column TESTCAMP row so every NOT NULL column is valid.
        W("DROP TEMPORARY TABLE IF EXISTS _cc;\n"
          "CREATE TEMPORARY TABLE _cc LIKE vicidial_campaigns;\n"
          f"INSERT INTO _cc SELECT * FROM vicidial_campaigns WHERE campaign_id='{CLONE_FROM}';\n"
          f"UPDATE _cc SET campaign_id='{c['id']}', campaign_name='{c['name']}', "
          f"user_group='{c['group']}', active='Y';\n"
          "INSERT IGNORE INTO vicidial_campaigns SELECT * FROM _cc;\n"
          "DROP TEMPORARY TABLE _cc;\n")
        for lid, lname in c['lists']:
            W(f"INSERT IGNORE INTO vicidial_lists (list_id, list_name, campaign_id, active, list_description) "
              f"VALUES ({lid},'{lname}','{c['id']}','Y','Demo tenant data - safe to delete');\n")
        for i, user in enumerate(agent_ids(c)):
            fn, ln = FIRST[i % 30], LAST[(i * 7 + 3) % 30]
            W(f"INSERT IGNORE INTO vicidial_users (user, pass, full_name, user_level, user_group, active, view_reports) "
              f"VALUES ('{user}','demo{100000 + int(user)}','{fn} {ln} (Demo)',1,'{c['group']}','Y','0');\n")

    if with_leads:
        W('-- ----- leads -----\n')
        leads = Tbl('vicidial_list',
                    'lead_id,entry_date,status,user,vendor_lead_code,list_id,gmt_offset_now,called_since_last_reset,'
                    'phone_code,phone_number,first_name,last_name,address1,city,state,postal_code,gender,called_count,'
                    'last_local_call_time')
        today = date.today()
        for c in CAMPAIGNS:
            if c.get('existing'):
                continue
            for lid, _ in c['lists']:
                lo, hi = lead_range(lid)
                W(f"DELETE FROM vicidial_list WHERE list_id={lid} AND vendor_lead_code LIKE 'MDL%';\n")
                for lead_id in range(lo, hi):
                    st_i = lead_id % 8
                    state, city, postal, gmt = STATES[st_i]
                    status = LEAD_STATUSES[lead_id % 1000]
                    called = 0 if status == 'NEW' else (lead_id % 4) + 1
                    fn, ln = FIRST[lead_id % 30], LAST[(lead_id // 30) % 30]
                    phone = 2_000_000_000 + lead_id
                    entry = today - timedelta(days=(lead_id % 180) + 1)
                    last_call = f"'{today - timedelta(days=lead_id % 45)} 12:00:00'" if called else 'NULL'
                    leads.add(f"({lead_id},'{entry} 10:00:00','{status}','','MDL{lead_id}',{lid},'{gmt}','Y','1',"
                              f"'{phone}','{fn}','{ln}','{(lead_id % 9000) + 100} {LAST[(lead_id // 7) % 30]} St',"
                              f"'{city}','{state}','{postal}','U',{called},{last_call})")
        leads.flush()


def emit_day(day, seq0):
    """One day of outbound data across every active campaign. Idempotent by markers."""
    today = date.today()
    now = datetime.now()
    wd = day.weekday()
    if wd == 6:                       # skip Sundays
        return seq0
    day_s = day.isoformat()
    nextday_s = (day + timedelta(days=1)).isoformat()
    base = int(time.mktime(day.timetuple()))
    day_compact = day_s.replace('-', '')
    is_today = day == today
    # deterministic shape per day
    random.seed(int(day_compact))
    rr, rnd = random.randrange, random.random

    # ---- idempotent wipe of this day's demo-daily footprint ----
    W(f"-- day {day_s}\n")
    W(f"DELETE FROM vicidial_log WHERE call_date>='{day_s} 00:00:00' AND call_date<'{nextday_s} 00:00:00' AND comments='DEMODAILY';\n")
    W(f"DELETE FROM vicidial_agent_log WHERE event_time>='{day_s} 00:00:00' AND event_time<'{nextday_s} 00:00:00' AND comments='DEMODAILY';\n")
    W(f"DELETE FROM vicidial_carrier_log WHERE call_date>='{day_s} 00:00:00' AND call_date<'{nextday_s} 00:00:00' AND caller_code LIKE 'MD%';\n")
    W(f"DELETE FROM vicidial_dial_log WHERE call_date>='{day_s} 00:00:00' AND call_date<'{nextday_s} 00:00:00' AND caller_code LIKE 'MD%';\n")
    W(f"DELETE FROM recording_log WHERE start_time>='{day_s} 00:00:00' AND start_time<'{nextday_s} 00:00:00' AND vicidial_id LIKE 'MD%';\n")

    vl = Tbl('vicidial_log', 'uniqueid,lead_id,list_id,campaign_id,call_date,start_epoch,end_epoch,length_in_sec,'
                             'status,phone_code,phone_number,user,comments,processed,user_group,term_reason,alt_dial,called_count')
    vcl = Tbl('vicidial_carrier_log', 'uniqueid,dialstatus,hangup_cause,channel,dial_time,answered_time,'
                                      'sip_hangup_cause,sip_hangup_reason,server_ip,call_date,lead_id,caller_code')
    vdl = Tbl('vicidial_dial_log', 'caller_code,lead_id,server_ip,call_date,extension,channel,context,timeout,'
                                   'outbound_cid,sip_hangup_cause,sip_hangup_reason,uniqueid')
    val = Tbl('vicidial_agent_log', 'user,server_ip,event_time,lead_id,campaign_id,pause_epoch,pause_sec,wait_epoch,'
                                    'wait_sec,talk_epoch,talk_sec,dispo_epoch,dispo_sec,status,user_group,comments,'
                                    'sub_status,dead_sec,uniqueid')
    rec = Tbl('recording_log', 'channel,server_ip,extension,start_time,start_epoch,end_time,end_epoch,length_in_sec,'
                               'length_in_min,filename,location,lead_id,user,vicidial_id')

    lo_s, hi_s = 9 * 3600, 18 * 3600
    if is_today and now.hour <= 18:
        hi_s = max(lo_s + 1800, now.hour * 3600 + now.minute * 60)
    seq = seq0
    for c in CAMPAIGNS:
        af = c.get('active_from')
        if af and day < af:
            continue
        agents = agent_ids(c)
        group = c['group']
        camp_lists = [lid for lid, _ in c['lists']] or None
        n_out = c['vol'] if wd < 5 else int(c['vol'] * 0.45)
        if is_today:
            if now.hour < 9:
                n_out = 0
            else:
                frac = min(1.0, ((now.hour - 9) * 60 + now.minute) / (9 * 60))
                n_out = int(n_out * frac)
        for _ in range(n_out):
            seq += 1
            sod = rr(lo_s, hi_s)
            sec = base + sod
            dt = f'{day_s} {sod // 3600:02d}:{(sod % 3600) // 60:02d}:{sod % 60:02d}'
            status, handled, lo, hi, dialstatus, cause, sip, reason, answered = OUT[rr(1000)]
            length = rr(lo, hi)
            if camp_lists:                       # tenant: lead from its own list pool
                list_id = camp_lists[seq % len(camp_lists)]
                llo, lhi = lead_range(list_id)
                lead = rr(llo, lhi)
            else:                                # TESTCAMP: reuse the 3M DEMO6M lead pool
                lead = rr(1_000_000, 4_000_000)
                list_id = 111 + lead % 12
            phone = 2_000_000_000 + lead
            uid = f'MD{sec}.{seq}'
            cc = f'MD{seq}'
            agent = agents[seq % len(agents)] if handled else 'VDAD'
            vl.add(f"('{uid}',{lead},{list_id},'{c['id']}','{dt}',{sec},{sec + length},{length},'{status}','1',"
                   f"'{phone}','{agent}','DEMODAILY','Y','{group}','{'AGENT' if handled else 'CALLER'}','MAIN',1)")
            vcl.add(f"('{uid}','{dialstatus}',{cause},'PJSIP/demo-{seq % 16777216:08x}',{rr(3, 28)},"
                    f"{length if answered else 0},{sip},'{reason}','{SIP}','{dt}',{lead},'{cc}')")
            vdl.add(f"('{cc}',{lead},'{SIP}','{dt}','91{phone}','Local/91{phone}@default','default','60',"
                    f"'\"DEMO\" <8005551234>',{sip},'{reason}','{uid}')")
            if handled:
                pause, wait, dispo = rr(0, 90), rr(3, 45), rr(8, 60)
                val.add(f"('{agent}','{SIP}','{dt}',{lead},'{c['id']}',{sec - wait - pause},{pause},{sec - wait},{wait},"
                        f"{sec},{length},{sec + length},{dispo},'{status}','{group}','DEMODAILY','',0,'{uid}')")
                if rnd() < 0.6:
                    fname = f"{c['id']}_{day_compact}-{sod // 3600:02d}{(sod % 3600) // 60:02d}{sod % 60:02d}_{agent}_{phone}"
                    loc = f'https://{HOST}/{AUDIO_DIR}/{AUDIO[seq % 5]}'
                    end_dt = f'{day_s} {(sod + length) // 3600:02d}:{((sod + length) % 3600) // 60:02d}:{(sod + length) % 60:02d}'
                    rec.add(f"('PJSIP/demo-{seq % 16777216:08x}','{SIP}','8309','{dt}',{sec},'{end_dt}',{sec + length},"
                            f"{length},'{length // 60}:{length % 60:02d}','{fname}','{loc}',{lead},'{agent}','{uid}')")
    for t in (vl, vcl, vdl, val, rec):
        t.flush()
    return seq


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--setup', action='store_true', help='emit campaigns/lists/agents/leads only')
    ap.add_argument('--backfill', type=int, metavar='DAYS', help='setup + generate the last DAYS days .. today')
    ap.add_argument('--date', metavar='YYYY-MM-DD', help='generate one specific day (no setup)')
    args = ap.parse_args()

    # NOTE: binlog is intentionally LEFT ON. db1 is the replication master for db2
    # (0s slave), so these writes must hit the binlog to reach db2. Run on db1 ONLY.
    W('SET SESSION bulk_insert_buffer_size=268435456;\n')

    if args.setup or args.backfill is not None:
        emit_setup(with_leads=True)
    if args.setup and args.backfill is None and not args.date:
        return

    today = date.today()
    if args.date:
        y, m, d = map(int, args.date.split('-'))
        days = [date(y, m, d)]
    elif args.backfill is not None:
        days = [today - timedelta(days=n) for n in range(args.backfill, -1, -1)]
    else:
        days = [today]                # cron default

    seq = 900_000_000
    for day in days:
        seq = emit_day(day, seq)
    sys.stderr.write(f'demo-daily: {len(days)} day(s), through seq {seq}\n')


if __name__ == '__main__':
    main()
